{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iaga-sentinel.fullname" . }}
  labels:
    {{- include "iaga-sentinel.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.secrets.receiptSignerKey }}
  receipt-signer-key: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.secrets.nhiMasterSeed }}
  nhi-master-seed: {{ . | b64enc }}
  {{- end }}
  {{- if .Values.secrets.apiKeys }}
  api-keys: {{ .Values.secrets.apiKeys | toJson | b64enc }}
  {{- end }}
  {{- if .Values.postgres.enabled }}
  {{- if and .Values.postgres.url (not .Values.postgres.existingSecret) }}
  database-url: {{ .Values.postgres.url | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
